export const HOME = "/home"
export const LOGIN = "/login"
export const REGISTER = "/register"
export const EVENTSMY = "/events/all"
export const EVENTSADD = "/events/add"
export const STUDENTS = "/students"
export const SETTINGS = "/settings"
export const ZOOMREDIRECT = "/zoom/callback"